export interface AIAgent {
  id: number;
  code: string;
  name: string;
  category: string;
  role: string;
  description: string;
  capabilities: string[];
  integrationTime: string;
  badgeColor: string;
  icon: string;
  promptSnippet: string;
  popular?: boolean;
}

export const AGENT_CATEGORIES = [
  { id: "all", label: "Todos los Agentes (250)", icon: "🤖" },
  { id: "educacion", label: "Educación & EdTech", icon: "🎓" },
  { id: "finanzas", label: "Finanzas & Contabilidad", icon: "📊" },
  { id: "govtech", label: "GovTech & Identidad", icon: "🆔" },
  { id: "soporte", label: "Soporte & Atención 24/7", icon: "💬" },
  { id: "ventas", label: "Ventas & E-Commerce B2B", icon: "📈" },
  { id: "devops", label: "DevOps & Cloud Server", icon: "⚡" },
  { id: "legal", label: "Legal & Cumplimiento", icon: "⚖️" },
  { id: "salud", label: "Salud & BioTech", icon: "🩺" },
  { id: "analitica", label: "Data & Analítica", icon: "🔮" },
  { id: "rrhh", label: "RRHH & Talento", icon: "👥" },
];

const categoryColors: Record<string, string> = {
  educacion: "bg-emerald-500/10 text-emerald-400 border-emerald-500/30",
  finanzas: "bg-[#A9843C]/20 text-[#A9843C] border-[#A9843C]/40",
  govtech: "bg-sky-500/10 text-sky-400 border-sky-500/30",
  soporte: "bg-purple-500/10 text-purple-400 border-purple-500/30",
  ventas: "bg-amber-500/10 text-amber-400 border-amber-500/30",
  devops: "bg-cyan-500/10 text-cyan-400 border-cyan-500/30",
  legal: "bg-rose-500/10 text-rose-400 border-rose-500/30",
  salud: "bg-teal-500/10 text-teal-400 border-teal-500/30",
  analitica: "bg-indigo-500/10 text-indigo-400 border-indigo-500/30",
  rrhh: "bg-pink-500/10 text-pink-400 border-pink-500/30",
};

// Helper function to generate 250 structured agents across 10 categories
function generate250Agents(): AIAgent[] {
  const agents: AIAgent[] = [];

  const categoryDefinitions = [
    {
      catId: "educacion",
      catName: "Educación & EdTech",
      prefix: "EDU",
      color: categoryColors.educacion,
      icon: "🎓",
      items: [
        { name: "Tutor Saber 11 Matemáticas", role: "Resolución de reactivos ICFES y explicaciones paso a paso de razonamiento cuantitativo." },
        { name: "Tutor Saber 11 Lectura Crítica", role: "Análisis de textos continuos y discontinuos con retroalimentación inmediata." },
        { name: "Tutor Bilingüe University English", role: "Práctica conversacional y gramática adaptativa alineada al marco MCER (A1-C1)." },
        { name: "Evaluador Automático de Rúbricas", role: "Calificación objetiva de ensayos y proyectos académicos con retroalimentación detallada." },
        { name: "Generador de Simulacros Adaptativos", role: "Creación dinámica de pruebas diagnósticas según el nivel individual del estudiante." },
        { name: "Asistente Integrador Campus Q10", role: "Consulta de notas, asistencia y horarios mediante API directa a Q10." },
        { name: "Mentor Vocacional & Becas", role: "Orientación profesional y recomendación personalizada de becas educativas." },
        { name: "Planificador de Clases Walpa", role: "Estructuración de micro-currículos y cronogramas de aprendizaje." },
        { name: "Tutor Fundetec Contalab", role: "Mentoría interactiva en registros contables y dinamización del PUC para técnicos." },
        { name: "Resumidor Académico PDF", role: "Extracción sintética de ideas clave de papers y guías de estudio complejas." },
        { name: "Tutor Saber 11 Ciencias Naturales", role: "Explicación de problemas de física, química y biología con simulación de preguntas." },
        { name: "Tutor Saber 11 Sociales y Ciudadanas", role: "Comprensión de contextos históricos, constitución y competencias ciudadanas." },
        { name: "Creador de Tarjetas Anki Flashcards", role: "Generación automática de mazos de memorización espaciada a partir de textos." },
        { name: "Monitor de Deserción Estudiantil", role: "Analítica predictiva de riesgo de retiro escolar a partir de interacción Q10." },
        { name: "Facilitador de Micro-certificaciones", role: "Generación y verificación de badges y diplomas digitales con firmas encriptadas." },
        { name: "Diseñador de Retos Diarios Fundetec", role: "Inyección diaria de quizzes y dinámicas de gamificación estudiantil." },
        { name: "Corrector de Ortografía & Estilo", role: "Revisión gramatical y estilística de monografías e informes técnicos." },
        { name: "Asistente de Laboratorio Virtual", role: "Simulación conversacional de protocolos de experimentación y seguridad." },
        { name: "Asistente de Inclusión & Lectura Fácil", role: "Adaptación de contenidos educativos para estudiantes con neurodiversidad." },
        { name: "Moderador de Foros Académicos", role: "Filtrado de comentarios y dinamización de debates grupales en el aula virtual." },
        { name: "Entrenador de Pronunciación Fonética", role: "Evaluación de audio y guía de fonética en inglés para docentes y alumnos." },
        { name: "Organizador de Bibliografía APA 7", role: "Formateo automático de referencias y citas académicas en norma APA 7." },
        { name: "Asistente de Admisiones Fundetec", role: "Guía interactiva para matrícula, requisitos y financiación de carreras técnicas." },
        { name: "Coach de Técnicas de Estudio", role: "Recomendación personalizada de metodologías Pomodoro, Feyman y mapas mentales." },
        { name: "Coordinador de Tareas y Alertas", role: "Recordatorio inteligente de entregas pendientes vía WhatsApp o correo notificativo." },
      ]
    },
    {
      catId: "finanzas",
      catName: "Finanzas & Contabilidad",
      prefix: "FIN",
      color: categoryColors.finanzas,
      icon: "📊",
      items: [
        { name: "Agente PUC Contable Colombia", role: "Clasificación automática de operaciones según el Plan Único de Cuentas." },
        { name: "Auditor de Facturación Electrónica DIAN", role: "Validación de archivos XML/CUFE y cruce de retenciones en la fuente." },
        { name: "Conciliador Bancario Inteligente", role: "Cruce de extractos bancarios contra libros auxiliares contables." },
        { name: "Calculador de Impuestos & NIIF", role: "Estimación de IVA, ICA y retenciones para pequeñas y medianas empresas." },
        { name: "Analista Flujo de Caja Predictivo", role: "Proyección de ingresos y egresos a 30, 60 y 90 días con detección de baches." },
        { name: "Revisor de Cuentas de Cobro & Viáticos", role: "Inspección de comprobantes y validación de soportes contables corporativos." },
        { name: "Cobrador Cartera Morosa Vía WhatsApp", role: "Envío programado y respetuoso de recordatorios de pago y acuerdos de cobro." },
        { name: "Validador de Lista Restrictiva SARLAFT", role: "Verificación de terceros en listas OFAC, Clinton y centrales de riesgo." },
        { name: "Generador de Estados Financieros", role: "Elaboración automática de Balance General y Estado de Resultados." },
        { name: "Controlador de Costos Operativos", role: "Identificación de desviaciones presupuestales en proyectos B2B." },
        { name: "Liquidador de Nómina & Seguridad Social", role: "Cálculo de retenciones, aportes a salud, pensión, ARL y parafiscales." },
        { name: "Inspector de Retención en la Fuente", role: "Determinación del porcentaje y base gravable según la normativa tributaria." },
        { name: "Gestor de Cuentas por Pagar Proveedores", role: "Programación de pagos a proveedores según fechas de vencimiento y descuentos." },
        { name: "Analista de Punto de Equilibrio", role: "Cálculo del volumen de ventas necesario para cubrir costos fijos y variables." },
        { name: "Auditor de Notas Débito y Crédito", role: "Verificación de causación y validez contable de anulación de facturas." },
        { name: "Simulador de Crédito & Amortización", role: "Generación de tablas de amortización con tasa fija, UVR o gradiente." },
        { name: "Asistente Exógena Tributaria DIAN", role: "Preparación de formatos de información exógena para presentación tributaria." },
        { name: "Rastreador de Gastos Hormiga", role: "Clasificación de micro-gastos corporativos para optimización de presupuestos." },
        { name: "Calculador de Rentabilidad Inmobiliaria", role: "Estimación de ROI, cap rate y flujo neto para inversiones Rentun Group." },
        { name: "Validador de Certificados de Libertad", role: "Extracción automática de anotaciones e hipotecas en matrículas inmobiliarias." },
        { name: "Agente Evaluador Riesgo Crediticio", role: "Calificación de perfil crediticio para arrendatarios y clientes B2B." },
        { name: "Gestor de Fondos de Caja Menor", role: "Registro de vales, reembolsos y legalizaciones de caja chica." },
        { name: "Analista de Márgenes Ebitda", role: "Medición en tiempo real del margen de utilidad operacional de la empresa." },
        { name: "Audit Bot Facturas Proveedores PDF", role: "Lectura OCR y extracción estructurada de conceptos de factura." },
        { name: "Consultor NIIF PyMES", role: "Respuestas normativas sobre aplicación de NIIF para PYMES en Colombia." },
      ]
    },
    {
      catId: "govtech",
      catName: "GovTech & Identidad",
      prefix: "GOV",
      color: categoryColors.govtech,
      icon: "🆔",
      items: [
        { name: "Cédula 360 Verification Engine", role: "Validación digital de documentos de identidad colombianos con lectura de código PDF417." },
        { name: "Cédula 360 Document Translate", role: "Traducción oficial multilingüe asistida de apostillas, títulos y antecedentes." },
        { name: "DeepMap Spatial Territorial Intelligence", role: "Geolocalización avanzada y mapas térmicos para inversión pública y privada." },
        { name: "Pulse Cloud Node Telemetry", role: "Supervisión 24/7 del estado de infraestructura pública y nodos GovTech." },
        { name: "Asistente de Trámites Registrales", role: "Guía interactiva para la realización de diligencias en notarías y cámaras de comercio." },
        { name: "Inspector Biométrico Facial", role: "Comparación de selfie en vivo contra fotografía de documento oficial." },
        { name: "Verificador de Licencias de Conducción", role: "Consulta automatizada de vigencia y categoría en el RUNT." },
        { name: "Gestor de Solicitudes PQRSD Ciudadanas", role: "Enrutamiento automático y seguimiento de peticiones a entidades públicas." },
        { name: "Auditor Contratación Secop I y II", role: "Búsqueda y monitoreo de licitaciones públicas según códigos UNSPSC." },
        { name: "Validador de Antecedentes Judiciales", role: "Consulta integrada en Policía, Procuraduría y Contraloría General." },
        { name: "Asistente Votaciones & Consultas", role: "Información de puestos de votación y jurados de votación en elecciones." },
        { name: "Extractor Datos Licencias de Construcción", role: "Digitalización de expedientes urbanísticos y permisos de curaduría." },
        { name: "Monitor de Planes de Desarrollo", role: "Seguimiento al cumplimiento de metas en planes de desarrollo municipal." },
        { name: "Asistente de Catastro Multipropósito", role: "Validación de avalúos catastrales y referencia predial municipal." },
        { name: "Verificador de SOAT & Tecnomecánica", role: "Alerta automática sobre vencimiento de pólizas y revisiones automotrices." },
        { name: "Agente Transparencia & Datos Abiertos", role: "Transformación de dataset públicos en tableros navegables." },
        { name: "Gestor Certificados Paz y Salvo", role: "Generación automática de paz y salvo impuesto predial e industria y comercio." },
        { name: "Inspector Normativo de Uso de Suelo", role: "Consulta de POT y compatibilidad de uso comercial según coordenada." },
        { name: "Asistente de Estratificación Social", role: "Certificación y consulta de estrato socioeconómico predial." },
        { name: "Validador Certificados de Nacimiento", role: "Revisión de actas y datos de registro civil de nacimiento o matrimonio." },
        { name: "Gestor Licencias Ambientales CAR", role: "Monitoreo de estado de trámites de permisos de agua, vertimientos y tala." },
        { name: "Analista de Movilidad & Tráfico", role: "Conteo y patrones de tráfico vehicular a través de analítica de video." },
        { name: "Agente Ventanilla Única de Trámites", role: "Portal unificado de radicación de documentos con firma electrónica." },
        { name: "Asistente Notarial Digital", role: "Generación de borradores de escrituras públicas, autenticaciones y poderes." },
        { name: "Verificador de Registro Único Tributario RUT", role: "Verificación de responsabilidades fiscales y actividad económica CIIU." },
      ]
    },
    {
      catId: "soporte",
      catName: "Soporte & Atención 24/7",
      prefix: "SUP",
      color: categoryColors.soporte,
      icon: "💬",
      items: [
        { name: "ErIkA Core AI Concierge", role: "Asistente institucional omnicanal del Holding con resolución en tiempo real." },
        { name: "Clasificador y Triador de Tickets", role: "Categorización automática de solicitudes entrantes por urgencia y temática." },
        { name: "Resolutor de Dudas Frecuentes FAQ", role: "Respuesta instantánea a más de 500 preguntas institucionales recurrentes." },
        { name: "Escalador Inteligente a Agente Humano", role: "Transferencia fluida de chats con contexto completo al equipo de soporte." },
        { name: "Atención WhatsApp Business Bot", role: "Interacción automatizada vía WhatsApp API con botones y menús." },
        { name: "Agente Recepcionista de Llamadas Voicemail", role: "Transcripción y síntesis de mensajes de voz dejados fuera de horario." },
        { name: "Encuestador de Satisfacción NPS", role: "Medición de experiencia del cliente y recopilación de métricas CSAT post-atención." },
        { name: "Moderador de Redes Sociales", role: "Respuesta automatizada a comentarios y mensajes en Instagram, Facebook y LinkedIn." },
        { name: "Traductor Omnicanal en Vivo", role: "Traducción simultánea en chats para clientes internacionales en 15+ idiomas." },
        { name: "Sintetizador de Caso & Bitácora", role: "Resumen ejecutivo de conversaciones complejas para archivo CRM." },
        { name: "Agente Guía de Navegación Web", role: "Orientación en vivo al visitante sobre donde encontrar soluciones en la web." },
        { name: "Rastreador de Envíos & Encomiendas", role: "Consulta en tiempo real del estado de paquetes y guía de despacho." },
        { name: "Agente Agendamiento de Citas Presenciales", role: "Reserva de espacios en agenda para atención presencial en sedes." },
        { name: "Controlador de Tiempos de Respuesta SLA", role: "Alerta en tiempo real sobre tiquetes a punto de vencer tiempo máximo." },
        { name: "Detector de Sentimiento del Cliente", role: "Análisis de frustración o enojo en el lenguaje del usuario para atención prioritaria." },
        { name: "Gestor de Cambios y Devoluciones", role: "Procesamiento paso a paso de garantías y solicitudes de reembolso." },
        { name: "Asistente de Restablecimiento de Claves", role: "Validación de identidad y envío seguro de enlaces de recuperación de contraseña." },
        { name: "Notificador de Interrupciones de Servicio", role: "Envío de alertas masivas sobre mantenimientos programados de sistemas." },
        { name: "Agente Onboarding Nuevos Clientes", role: "Guía de bienvenida interactiva paso a paso para usuarios recién registrados." },
        { name: "Consultor de Políticas de Privacidad", role: "Explicación directa sobre manejo de datos personales y solicitudes ARCO." },
        { name: "Agente Reivindicador de Experiencia", role: "Ofrecimiento de disculpas institucionales y cupones de compensación." },
        { name: "Auditor de Calidad de Chats", role: "Evaluación periódica del nivel de amabilidad y precisión de respuestas." },
        { name: "Coordinador de Soporte Remoto ScreenShare", role: "Generación de enlaces de asistencia remota para fallas de software." },
        { name: "Agente de Bienvenida a Eventos Webinars", role: "Confirmación de asistencia e información de acceso a salas virtuales." },
        { name: "Gestor de FAQ Dinámicas Auto-aprendices", role: "Actualización automática de base de conocimiento basada en preguntas no resueltas." },
      ]
    },
    {
      catId: "ventas",
      catName: "Ventas & E-Commerce B2B",
      prefix: "SAL",
      color: categoryColors.ventas,
      icon: "📈",
      items: [
        { name: "Cotizador Automático Web & SaaS", role: "Generación instantánea de presupuestos personalizados en PDF según requerimientos." },
        { name: "Calificador de Leads B2B (BANT)", role: "Evaluación de presupuesto, autoridad, necesidad y tiempo de compra de prospectos." },
        { name: "Prospectador B2B LinkedIn", role: "Identificación de decisores de compra y redacción de secuencias de contacto." },
        { name: "Recuperador de Carritos Abandonados", role: "Notificaciones persuasivas automatizadas para concretar ventas pendientes." },
        { name: "Creador de Propuestas Comerciales", role: "Redacción de propuestas corporativas a medida con desglose de servicios." },
        { name: "Recomendador de Productos Upsell", role: "Venta cruzada inteligente basada en el historial y perfil del comprador." },
        { name: "Agente Demo Interactivo", role: "Guía conversacional para mostrar funcionalidades clave de plataformas SaaS." },
        { name: "Organizador de Agenda Comercial", role: "Sincronización automática de reuniones de ventas con Google Calendar." },
        { name: "Simulador de Precios y Descuentos", role: "Cálculo de tarifas por volumen, suscripciones anuales y promociones." },
        { name: "Enrutador de Oportunidades por Zona", role: "Asignación de leads al ejecutivo comercial responsable según la ciudad." },
        { name: "Extractor de Datos de Licitaciones B2B", role: "Detección de convocatorias privadas de software y consultoría." },
        { name: "Cierre de Ventas por WhatsApp", role: "Conducción del embudo de ventas hasta el enlace de pago seguro." },
        { name: "Analista de Competencia & Precios", role: "Monitoreo de mercado y comparación de propuestas comerciales." },
        { name: "Generador de Testimonios y Casos de Éxito", role: "Entrevistas automáticas post-venta para creación de reseñas." },
        { name: "Calculador de CAC y LTV", role: "Seguimiento al costo de adquisición de clientes y valor de vida útil." },
        { name: "Optimizador de Copywriting Publicitario", role: "Generación de anuncios para Meta Ads y Google Ads con alta conversión." },
        { name: "Asistente de Negociación de Tarifas", role: "Manejo de objeciones de precio y alternativas de financiación." },
        { name: "Gestor de Alianzas y Partners B2B", role: "Onboarding y seguimiento a la red de afiliados y socios distribuidores." },
        { name: "Agente de Reactivación de Clientes Inactivos", role: "Campañas automatizadas para recuperar cuentas sin compras recientes." },
        { name: "Creador de Landing Pages de Conversión", role: "Generación de estructura y textos persuasivos para páginas de venta." },
        { name: "Verificador de Stock & Inventario", role: "Consulta en tiempo real de disponibilidad antes de confirmar la compra." },
        { name: "Agente de Cobro de Anticipos", role: "Seguimiento al pago del 50% de inicial previo al inicio de desarrollo." },
        { name: "Asistente de Contratación Comercial", role: "Envío y firma digital de ofertas acordadas entre las partes." },
        { name: "Analista de Embudo de Conversión Funnel", role: "Identificación de puntos de fuga en cada etapa del proceso de ventas." },
        { name: "Notificador de Metas de Ventas Team", role: "Publicación de avances de facturación del equipo en Slack o Teams." },
      ]
    },
    {
      catId: "devops",
      catName: "DevOps & Cloud Server",
      prefix: "DEV",
      color: categoryColors.devops,
      icon: "⚡",
      items: [
        { name: "Ollama Local Engine Controller", role: "Monitoreo y orquestación de modelos de lenguaje privados en VPS Hostinger." },
        { name: "Monitor de Salud Cloud 24/7", role: "Supervisión de uptime, latencia, CPU y memoria RAM de servidores cloud." },
        { name: "Auditor de Seguridad Supabase & SQL", role: "Inspección de políticas RLS, índices y prevención de inyecciones SQL." },
        { name: "Deployer CI/CD Vercel & Docker", role: "Automatización de despliegues continuos y pruebas pre-despliegue." },
        { name: "Optimizador de Costos AWS / GCP", role: "Análisis de recursos subutilizados para reducir la factura mensual de cloud." },
        { name: "Gestor de SSL & Dominios DNS", role: "Renovación automática de certificados HTTPS y resolución de registros DNS." },
        { name: "Analista de Logs & Stack Traces", role: "Lectura inmediata de errores en producción y sugerencia de parches." },
        { name: "Generador de Pruebas Unitarias Jest", role: "Creación automática de suites de test para frontend y backend." },
        { name: "Inspector de Performance Web Vitals", role: "Medición de LCP, CLS y FID con recomendaciones de optimización Next.js." },
        { name: "Gestor de Backups y Snapshots", role: "Programación y verificación de copias de seguridad de bases de datos." },
        { name: "Bot de Respuesta a Incidentes PagerDuty", role: "Alerta y mitigación automática ante caídas de servicios críticos." },
        { name: "Auditor de Paquetes Vulnerables npm", role: "Detección de librerías desactualizadas o con fallos de seguridad conocidos." },
        { name: "Configurador de Contenedores Docker", role: "Generación de Dockerfile y docker-compose optimizados para producción." },
        { name: "Agente de Migración de Bases de Datos", role: "Ejecución controlada de scripts SQL de migración sin ddown-time." },
        { name: "Simulador de Carga & Pruebas de Estrés", role: "Generación de peticiones concurrentes para medir límites del servidor." },
        { name: "Gestor de Secretos & Variables de Entorno", role: "Almacenamiento encriptado de API Keys y tokens de servicio." },
        { name: "Optimizador de Caché CDN Cloudflare", role: "Configuración de reglas de caché de borde para acelerar la carga web." },
        { name: "Linter & Corrector de Código Limpio", role: "Aplicación automática de normas ESLint, Prettier y buenas prácticas." },
        { name: "Analista de API Endpoints REST/GraphQL", role: "Documentación automática OpenAPI / Swagger y pruebas de endpoints." },
        { name: "Monitor de Ancho de Banda & Consumo", role: "Alerta por tráfico inusual o posibles ataques de denegación DDoS." },
        { name: "Agente de Microservicios Kubernetes", role: "Despliegue y escalado horizontal de pods en clústeres K8s." },
        { name: "Verificador de Compatibilidad Cross-Browser", role: "Auditoría de rendering en Safari, Chrome, Firefox y dispositivos móviles." },
        { name: "Generador de Diagramas de Arquitectura C4", role: "Creación automática de mapas de infraestructura en formato Mermaid." },
        { name: "Gestor de Git Pull Requests Reviewer", role: "Revisión automática de código en PRs antes de hacer merge a main." },
        { name: "Monitor de Tiempos de Respuesta DB Query", role: "Detección de consultas SQL lentas y sugerencia de creación de índices." },
      ]
    },
    {
      catId: "legal",
      catName: "Legal & Cumplimiento",
      prefix: "LEG",
      color: categoryColors.legal,
      icon: "⚖️",
      items: [
        { name: "Auditor Habeas Data & Ley 1581", role: "Verificación del cumplimiento de políticas de protección de datos personales." },
        { name: "Generador de Contratos B2B y NDA", role: "Redacción automatizada de acuerdos de confidencialidad y prestación de servicios." },
        { name: "Inspector Términos y Condiciones Web", role: "Revisión de cláusulas legales y responsabilidad en plataformas digitales." },
        { name: "Gestor de PQR con Términos Legales", role: "Respuestas motivadas dentro de los plazos fijados por el derecho de petición." },
        { name: "Validador de Firmas Digitales y OTP", role: "Comprobación de validez jurídica de firmas electrónicas en contratos." },
        { name: "Agente de Cumplimiento Normativo SG-SST", role: "Seguimiento a estándares mínimos del sistema de gestión de seguridad en el trabajo." },
        { name: "Auditor de Licencias de Software Open Source", role: "Verificación de compatibilidad de licencias MIT, GPL y Apache." },
        { name: "Redactor de Contratos Laborales Ley Colombia", role: "Generación de contratos a término fijo, indefinido y por obra o labor." },
        { name: "Inspector de Propiedad Intelectual & Marcas", role: "Búsqueda de antecedentes marcarios en la Superintendencia de Industria y Comercio." },
        { name: "Gestor de Pólizas de Cumplimiento & RCE", role: "Verificación de vigencia y coberturas en seguros de ejecución contractual." },
        { name: "Asistente de Trámites de Tutela & Respuestas", role: "Estructuración de respuestas fundamentadas a acciones de tutela." },
        { name: "Agente de Gobierno Corporativo & Socios", role: "Redacción de actas de asamblea de accionistas y juntas directivas." },
        { name: "Auditor de Normas ISO 27001 Seguridad", role: "Evaluación del cumplimiento de controles de seguridad de la información." },
        { name: "Redactor de Matriz de Riesgos Legales", role: "Identificación y mitigación de eventualidades judiciales para la empresa." },
        { name: "Asistente de Liquidación de Contratos Laborales", role: "Cálculo de cesantías, intereses, prima y vacaciones de ley." },
        { name: "Gestor de Políticas de Cookies & Privacidad", role: "Configuración y actualización de banners de consentimiento de navegación." },
        { name: "Inspector de Cláusulas Abusivas en Arriendos", role: "Revisión de contratos de arrendamiento comercial para Rentun Group." },
        { name: "Asistente de Reclamos por Derecho del Consumidor", role: "Atención de inconformidades según el estatuto del consumidor Ley 1480." },
        { name: "Auditor de Transparencia & Anticorrupción", role: "Monitoreo de canales de denuncia anónima y código de ética." },
        { name: "Redactor de Acuerdos de Nivel de Servicio SLA", role: "Definición legal de tiempos de respuesta y penalizaciones por incumplimiento." },
        { name: "Asistente de Trámites ante Notarías Digitales", role: "Preparación de minutas para autenticación y escrituración remota." },
        { name: "Auditor de Cumplimiento Normativo DIAN UIAF", role: "Monitoreo de reporte de operaciones sospechosas en el sector financiero." },
        { name: "Redactor de Estatutos para Nuevas Sociedades SAS", role: "Creación de minutas de constitución de empresas de acciones simplificadas." },
        { name: "Agente de Custodia y Archivo Documental", role: "Clasificación legal de documentos según tabla de retención documental TRD." },
        { name: "Inspector de Acuerdos de Licenciamiento SaaS", role: "Redacción de términos EULA de acceso a software bajo suscripción." },
      ]
    },
    {
      catId: "salud",
      catName: "Salud & BioTech",
      prefix: "HLT",
      color: categoryColors.salud,
      icon: "🩺",
      items: [
        { name: "Asistente de Triage & Orientación Médica", role: "Evaluación sintomática previa para canalización eficiente de consultas." },
        { name: "Agendador de Citas Médicas & Exámenes", role: "Coordinación automática de espacios en agenda con especialidades médicas." },
        { name: "Recordador de Medicamentos & Adherencia", role: "Mensajes interactivos para recordar tomas de tratamiento a pacientes." },
        { name: "Resumidor de Historias Clínicas", role: "Extracción sintética de antecedentes y diagnósticos para consulta médica." },
        { name: "Auditor de Cuentas Médicas & RIPS", role: "Validación de archivos RIPS y códigos CIE-10 / CUPS para facturación." },
        { name: "Asistente de Orientación en Nutrición", role: "Sugerencias de planes alimenticios balanceados según objetivos de salud." },
        { name: "Monitor de Signos Vitales Telemedicina", role: "Recepción y alerta ante valores anómalos de presión o glucosa." },
        { name: "Agente de Apoyo Psicológico Inicial", role: "Escucha empática y canalización inmediata a líneas de atención profesional." },
        { name: "Extractor de Resultados de Laboratorio", role: "Digitalización y explicación en lenguaje sencillo de exámenes de sangre." },
        { name: "Gestor de Autorizaciones EPS & Prepagada", role: "Seguimiento al estado de aprobación de órdenes de procedimientos quirúrgicos." },
        { name: "Orientador de Cuidado de Adulto Mayor", role: "Recomendaciones de rutina de ejercicios suaves y prevención de caídas." },
        { name: "Asistente de Odontología Preventiva", role: "Recordatorio de controles semestrales y tips de higiene bucal." },
        { name: "Auditor de Bioseguridad e Higiene Hospitalaria", role: "Checklist interactivo de verificación de protocolos de esterilización." },
        { name: "Agente de Programación de Cirugías", role: "Coordinación de reserva de quirófano, anestesiólogo e insumos." },
        { name: "Validador de Fórmulas Médicas & Dosis", role: "Verificación de posología y prevención de interacciones farmacológicas." },
        { name: "Gestor de Incapacidades Médicas", role: "Validación y radicación de certificados de incapacidad ante la EPS." },
        { name: "Asistente de Salud Ocupacional & Ergonomía", role: "Tips de pausas activas y posturas de trabajo frente al computador." },
        { name: "Orientador de Salud Visual & Optometría", role: "Guía de síntomas de fatiga ocular y agenda para examen de optometría." },
        { name: "Gestor de Ensayos Clínicos & Voluntarios", role: "Filtro de criterios de inclusión y exclusión para investigaciones biomédicas." },
        { name: "Asistente de Vacunación & Esquemas", role: "Verificación de dosis aplicadas y alertas de refuerzos según edad." },
        { name: "Trazador Epidemiológico de Infecciones", role: "Monitoreo de brotes virales y aislamiento preventivo institucional." },
        { name: "Agente de Maternidad & Control Prenatal", role: "Seguimiento semana a semana del embarazo y fechas de ecografías." },
        { name: "Auditor de Inventario Farmacéutico", role: "Alertas de semaforización por fecha de vencimiento de medicamentos." },
        { name: "Asistente de Fisioterapia & Rehabilitación", role: "Guía ilustrada de ejercicios de estiramiento y recuperación." },
        { name: "Gestor de Ambulancias & Urgencias Vitales", role: "Despacho prioritario con geolocalización en casos de emergencia." },
      ]
    },
    {
      catId: "analitica",
      catName: "Data & Analítica",
      prefix: "DAT",
      color: categoryColors.analitica,
      icon: "🔮",
      items: [
        { name: "Generador de Dashboards Ejecutivos", role: "Creación de paneles interactivos de métricas clave KPI en tiempo real." },
        { name: "Extractor de Insights de Negocio", role: "Identificación de patrones ocultos y tendencias en bases de datos." },
        { name: "Predictor de Ventas & Demanda", role: "Modelamiento estadístico para estimar ventas futuras de productos." },
        { name: "Sintetizador de Reportes Mensuales", role: "Redacción automática de informes narrativos de gestión para la gerencia." },
        { name: "Segmentador de Clientes RFM", role: "Clasificación de usuarios por recencia, frecuencia y valor monetario." },
        { name: "Analista de Sentimiento de Marca", role: "Medición de opinión pública y menciones en medios digitales." },
        { name: "Limpiador & Depurador de Datos", role: "Normalización de nombres, correos y eliminación de duplicados." },
        { name: "Extractor ETL de Bases de Datos", role: "Automatización de pipelines de extracción, transformación y carga." },
        { name: "Predictor de Pérdida de Clientes (Churn)", role: "Alerta temprana sobre usuarios con alta probabilidad de cancelar." },
        { name: "Analista de Tráfico Web Google Analytics 4", role: "Interpretación de embudos, tasa de rebote y tiempo de permanencia." },
        { name: "Generador de Consultas SQL Complejas", role: "Conversión de preguntas en lenguaje natural a código SQL optimizado." },
        { name: "Auditor de Calidad de Datos Data Quality", role: "Medición de completitud, consistencia y exactitud del dataset." },
        { name: "Calculador de Elasticidad de Precios", role: "Simulación del impacto de cambios de precio en el volumen demandado." },
        { name: "Analista de Canales de Atribución Marketing", role: "Identificación de las fuentes de tráfico que más generan conversiones." },
        { name: "Analizador de Big Data PySpark / BigQuery", role: "Procesamiento distribuido de millones de registros en segundos." },
        { name: "Generador de Mapas de Calor de Navegación", role: "Análisis de clics y scroll en interfaces web para mejorar UX." },
        { name: "Visualizador de Grafos de Relaciones", role: "Mapeo de conexiones entre empresas, clientes y proyectos." },
        { name: "Analista de Productividad Operativa", role: "Medición de tiempos de ejecución de tareas por departamentos." },
        { name: "Predictor de Mantenimiento Preventivo Equipment", role: "Estimación de fallas mecánicas en hardware antes de que ocurran." },
        { name: "Generador de Benchmarks de Industria", role: "Comparación de métricas de la empresa contra el promedio del sector." },
        { name: "Analista de Cohortes de Retención", role: "Seguimiento al comportamiento de grupos de usuarios a lo largo del tiempo." },
        { name: "Agente de Web Scraping Etico", role: "Extracción estructurada de precios e información pública de competidores." },
        { name: "Sintetizador de Audio a Texto Transcriptor", role: "Conversión de reuniones grabadas en minutas ejecutivas con compromisos." },
        { name: "Analista de Canasta de Compra Market Basket", role: "Identificación de productos que se compran frecuentemente juntos." },
        { name: "Detector de Anomalías & Fraude", role: "Identificación instantánea de transacciones o patrones sospechosos." },
      ]
    },
    {
      catId: "rrhh",
      catName: "RRHH & Talento",
      prefix: "HRM",
      color: categoryColors.rrhh,
      icon: "👥",
      items: [
        { name: "Filtrador & Evaluador de Hojas de Vida", role: "Lectura OCR y puntuación de CVs según perfil del cargo requerido." },
        { name: "Entrevistador de Selección IA", role: "Simulación de entrevistas iniciales por competencias con informe de idoneidad." },
        { name: "Agente de Onboarding Laboral", role: "Acompañamiento en el primer día, entrega de credenciales y guías de la empresa." },
        { name: "Medidor de Clima Organizacional", role: "Aplicación anónima de encuestas de clima laboral y análisis de cultura." },
        { name: "Planificador de Capacitaciones Internas", role: "Asignación y seguimiento a cursos de formación técnica de empleados." },
        { name: "Evaluador de Desempeño 360 Grados", role: "Consolidación de evaluaciones de jefes, pares y subordinados." },
        { name: "Gestor de Solicitudes de Vacaciones & Permisos", role: "Aprobación y control de días de descanso disponibles por empleado." },
        { name: "Analista de Rotación de Personal", role: "Identificación de motivos de renuncia y estrategias de fidelización." },
        { name: "Redactor de Perfiles de Cargo & Manuales", role: "Estructuración de funciones, requisitos y competencias para vacantes." },
        { name: "Publicador de Ofertas Laborales Multisitio", role: "Difusión automática de vacantes en LinkedIn, Computrabajo y elempleo." },
        { name: "Asistente de Bienestar Estudiantil & Docente", role: "Atención a inquietudes de la comunidad educativa Fundetec." },
        { name: "Calculador de Horas Extra y Recargos", role: "Registro exacto de horas nocturnas, festivas y dominicales." },
        { name: "Coach de Liderazgo Jowhalth Academy", role: "Tips interactivos diarios de gestión de equipos para directivos." },
        { name: "Gestor de Exámenes Médicos Ocupacionales", role: "Programación de evaluaciones de ingreso, periódicas y de egreso." },
        { name: "Auditor de Entrega de Dotación Laboral", role: "Control de firmas de entrega de uniformes y elementos de protección EPP." },
        { name: "Asistente de Comités Paritarios COPASST", role: "Convocatoria y redacción de actas de reuniones mensuales del comité." },
        { name: "Gestor de Reconocimientos & Premios", role: "Dinámicas de gamificación para felicitar cumpleaños y logros del equipo." },
        { name: "Analista de Equidad Salarial", role: "Comparación de bandas salariales internas frente al mercado laboral." },
        { name: "Asistente de Teletrabajo & Trabajo Híbrido", role: "Acuerdos de desconexión digital y listas de chequeo ergonómicas." },
        { name: "Agente de Prevención de Burnout", role: "Alertas tempranas sobre sobrecarga laboral y sugerencia de pausas." },
        { name: "Gestor de Certificados Laborales PDF", role: "Expedición automática de certificaciones de trabajo con código QR." },
        { name: "Orientador de Plan de Carrera", role: "Mapeo de rutas de ascenso y habilidades necesarias para subir de cargo." },
        { name: "Asistente de Conciliación de Conflictos Laborales", role: "Guía de comunicación asertiva para la resolución de malentendidos." },
        { name: "Organizador de Eventos de Integración Team", role: "Encuestas de preferencias y logística de jornadas de integración." },
        { name: "Auditor de Archivos de Hoja de Vida Kárdex", role: "Verificación de documentos completos en la carpeta física y digital." },
      ]
    }
  ];

  let idCounter = 1;

  for (const cat of categoryDefinitions) {
    cat.items.forEach((item, idx) => {
      const codeNumber = (idx + 1).toString().padStart(3, "0");
      agents.push({
        id: idCounter,
        code: `AGENT-${cat.prefix}-${codeNumber}`,
        name: item.name,
        category: cat.catId,
        role: cat.catName,
        description: `${item.role} Diseñado para integrarse vía API, webhook o widget flotante en proyectos institucionales y empresariales.`,
        capabilities: [
          item.role,
          "Inferencia ultrarrápida en servidor privado Ollama LLM / Cloud API.",
          "Sincronización bidireccional con bases de datos Supabase / PostgreSQL.",
          "Historial conversacional encriptado y soporte omnicanal."
        ],
        integrationTime: "< 24 Horas",
        badgeColor: cat.color,
        icon: cat.icon,
        promptSnippet: `Eres el ${item.name}, un agente experto especializado de la red WP Ecosystem. Tu misión principal es: ${item.role}. Responde siempre en español profesional, con precisión técnica y orientación ejecutiva al cliente.`,
        popular: idx < 3
      });
      idCounter++;
    });
  }

  return agents;
}

export const ALL_AGENTS: AIAgent[] = generate250Agents();
